# Generated by Django 5.1.7 on 2025-04-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechStartup', '0002_rename_manufacturer_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='website',
        ),
    ]
