# Generated by Django 5.1.7 on 2025-05-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechStartup', '0003_remove_manufacturer_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='spec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
